title: Jin Hyeok Noh
description: Data Scientist
site_title: '@jinnoh47 - Jin Hyeok Noh'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: jinnoh47
blog_url: https://www.jinnoh47.github.io
email: jhnoh47@gmail.com
keybase_username: jinnoh47
twitter_username: jinnoh47
reddit_username: jinnoh47

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 